CREATE DATABASE HR;

CREATE TABLE JOBS (
    JOB_ID   NUMBER(10, 0) NOT NULL,
    JOB_NAME VARCHAR2(100),

    CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID)
);


CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER(10, 0) NOT NULL,
    LOCATION_NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(10, 0) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100),
    MANAGER_ID      NUMBER(10, 0),
    LOCATION_ID   NUMBER(10, 0) NOT NULL,

    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS(MANAGER_ID),
    CONSTRAINT FK_LOCATION_REF_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE MANAGERS (
    MANAGER_ID    NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID NUMBER(10, 0) NOT NULL,
    MANAGER_NAME  VARCHAR2(100),


    CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID    NUMBER(10, 0) NOT NULL,
    FIRST_NAME     VARCHAR2(100) NOT NULL,
    LAST_NAME      VARCHAR2(100),
    EMAIL          VARCHAR2(100) NOT NULL,
    PHONE_NUMBER   NUMBER(10, 0),
    HIRED_DATE     DATE,
    JOB_ID         NUMBER(10, 0) NOT NULL,
    SALARY         NUMBER(10, 0),
    COMMISSION_PCT NUMBER(10, 0),
    MANAGER_ID     NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID  NUMBER(10, 0) NOT NULL,


    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_JOB_REF_JOBS FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

--

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM  EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS
    WHERE LAST_NAME IN ('Marketing', 'Administration'));

SELECT FIRST_NAME, JOB_ID,
DECODE(JOB_ID,
    'IT_PROG', 'Programador',
    'FI_ACCOUNT', 'Contador',
    'VERIFICAR') CARGO
FROM EMPLOYEES;

SELECT FIRST_NAME,JOB_ID, SALARY,
       CASE
           WHEN SALARY < 5000 THEN 'AUMENTO'
           WHEN SALARY > 10000 THEN 'VERIFICAR'
           ELSE 'NÃO AUMENTAR'
           END VERIFICAR_AUMENTO
FROM EMPLOYEES
