CREATE DATABASE HR;

CREATE TABLE JOBS
(
    JOB_ID   NUMBER(10, 0) NOT NULL,
    JOB_NAME VARCHAR2(100),

    CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID)
);


CREATE TABLE LOCATIONS
(
    LOCATION_ID   NUMBER(10, 0) NOT NULL,
    LOCATION_NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE DEPARTMENTS
(
    DEPARTMENT_ID   NUMBER(10, 0) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100),
    MANAGER_ID      NUMBER(10, 0),
    LOCATION_ID     NUMBER(10, 0) NOT NULL,

    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS (MANAGER_ID),
    CONSTRAINT FK_LOCATION_REF_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS (LOCATION_ID)
);

CREATE TABLE MANAGERS
(
    MANAGER_ID    NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID NUMBER(10, 0) NOT NULL,
    MANAGER_NAME  VARCHAR2(100),


    CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID    NUMBER(10, 0) NOT NULL,
    FIRST_NAME     VARCHAR2(100) NOT NULL,
    LAST_NAME      VARCHAR2(100),
    EMAIL          VARCHAR2(100) NOT NULL,
    PHONE_NUMBER   NUMBER(10, 0),
    HIRED_DATE     DATE,
    JOB_ID         NUMBER(10, 0) NOT NULL,
    SALARY         NUMBER(10, 0),
    COMMISSION_PCT NUMBER(10, 0),
    MANAGER_ID     NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID  NUMBER(10, 0) NOT NULL,


    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_JOB_REF_JOBS FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

-- PLAYER DB
CREATE DATABASE PLAYERS;

CREATE TABLE PLAYER(
    ID_player NUMBER(10, 0) NOT NULL,
    name      VARCHAR2(100) NOT NULL,
    position  VARCHAR2(100),
    nickname  VARCHAR2(100),

    Constraint PK_player Primary Key (ID_player)
);


CREATE TABLE HIRED(
    ID_player    NUMBER(10, 0) NOT NULL,
    Initial_date DATE          NOT NULL,
    final_date   DATE          NOT NULL,

    Constraint PK_Hired Primary key (ID_player, Initial_date),
    Constraint FK_Hired_Ref_Player Foreign key (ID_player)
        references PLAYER (ID_player),
    Constraint CK_Hired CHECK (final_date > Initial_date)
);
--

SET SERVEROUTPUT ON;

DECLARE
    C_EMPLOYESS IS
    SELECT FIRST_NAME, SALARY FROM EMPLOYESS;
    V_NAME        VARCHAR2(30);
    V_SALARY      EMPLOYEES.SALARY%TYPE;
    V_TOTALSALARY NUMBER(8, 2);

BEGIN
    V_TOTALSALARY := 0

    OPEN C_EMPLOYESS;

    LOOP
        FETCH C_EMPLOYESS INTO V_NAME, V_SALARY;

        DBMS_OUTPUT.PUT_LINE(V_NAME);
        V_TOTALSALARY := V_TOTALSALARY + V_SALARY;

        EXIT WHEN C_EMPLOYESS%NOTFOUND;
    END LOOP;
    CLOSE C_EMPLOYESS;
END;


CREATE OR REPLACE PROCEDURE ADD_NEW_PLAYER(
PLAYER_ID_IN IN NUMBER,
PLAYER_NAME_IN IN VARCHAR2,
PLAYER_PLACE_IN IN NUMBER,
PLAYER_NICKNAME_IN IN VARCHAR2)
IS BEGIN
    INSERT
    INTO PLAYER(ID_player, name, position, nickname)
    VALUES (PLAYER_ID_IN, PLAYER_NAME_IN, PLAYER_PLACE_IN, PLAYER_NICKNAME_IN);
END;

--
EXEC ADD_NEW_PLAYER(3, 'player 3', 99, 'Iniciante');
