CREATE DATABASE HR;

CREATE TABLE JOBS (
    JOB_ID      NUMBER(10,0) NOT NULL,
    JOB_NAME    VARCHAR2(100),

    CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID)
);

CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID    NUMBER(10,0) NOT NULL,
  DEPARTMENT_NAME  VARCHAR2(100),

  CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE MANAGERS (
    MANAGER_ID          NUMBER(10,0) NOT NULL,
    DEPARTMENT_ID       NUMBER(10,0) NOT NULL,
    MANAGER_NAME        VARCHAR2(100),


    CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
                      REFERENCES DEPARTMENTS(DEPARTMENT_ID)

);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID          NUMBER(10,0) NOT NULL,
    FIRST_NAME          VARCHAR2(100) NOT NULL,
    LAST_NAME           VARCHAR2(100),
    EMAIL               VARCHAR2(100) NOT NULL,
    PHONE_NUMBER        NUMBER(10,0),
    HIRED_DATE          DATE,
    JOB_ID              NUMBER(10,0) NOT NULL,
    SALARY              NUMBER(10,0),
    COMMISSION_PCT      NUMBER(10,0),
    MANAGER_ID          NUMBER(10,0) NOT NULL,
    DEPARTMENT_ID      NUMBER(10,0) NOT NULL,


    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_JOB_REF_JOBS FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS(MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
                       REFERENCES DEPARTMENTS(DEPARTMENT_ID)

);

--

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID NOT IN (101, 145, 149);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%'; -- '%s%'  '%a'
-- WHERE FIRST_NAME NOT LIKE 'S%'; -- '%s%'  '%a'


SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 2600;
-- WHERE SALARY NOT BETWEEN 2500 AND 2600;

INSERT INTO JOBS (JOB_ID, JOB_NAME) VALUES (1, 'Assistente Adminsitrativo');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (1, 'Departamento Pessoal');

INSERT INTO MANAGERS (MANAGER_ID, DEPARTMENT_ID, MANAGER_NAME) VALUES (1, 1, 'MARIAH');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRED_DATE, JOB_ID, SALARY,
                       COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (1, 'Karla cristina', 'Brouw', 'karla@k.com', 0000000000, TO_DATE('10-01-2021'), 1, 15000, null, 1, 1)

UPDATE JOBS SET JOB_NAME = 'Gerente de Departamento Pessoal'
WHERE JOB_ID = 1;

INSERT INTO JOBS (JOB_ID, JOB_NAME) VALUES (2, 'Assistente Adminsitrativo');

DELETE FROM JOBS WHERE JOB_ID = 2;

