CREATE DATABASE HR;

CREATE TABLE JOBS
(
    JOB_ID   NUMBER(10, 0) NOT NULL,
    JOB_NAME VARCHAR2(100),

    CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID)
);


CREATE TABLE LOCATIONS
(
    LOCATION_ID   NUMBER(10, 0) NOT NULL,
    LOCATION_NAME VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE DEPARTMENTS
(
    DEPARTMENT_ID   NUMBER(10, 0) NOT NULL,
    DEPARTMENT_NAME VARCHAR2(100),
    MANAGER_ID      NUMBER(10, 0),
    LOCATION_ID     NUMBER(10, 0) NOT NULL,

    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS (MANAGER_ID),
    CONSTRAINT FK_LOCATION_REF_LOCATION FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS (LOCATION_ID)
);

CREATE TABLE MANAGERS
(
    MANAGER_ID    NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID NUMBER(10, 0) NOT NULL,
    MANAGER_NAME  VARCHAR2(100),


    CONSTRAINT PK_MANAGER PRIMARY KEY (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID    NUMBER(10, 0) NOT NULL,
    FIRST_NAME     VARCHAR2(100) NOT NULL,
    LAST_NAME      VARCHAR2(100),
    EMAIL          VARCHAR2(100) NOT NULL,
    PHONE_NUMBER   NUMBER(10, 0),
    HIRED_DATE     DATE,
    JOB_ID         NUMBER(10, 0) NOT NULL,
    SALARY         NUMBER(10, 0),
    COMMISSION_PCT NUMBER(10, 0),
    MANAGER_ID     NUMBER(10, 0) NOT NULL,
    DEPARTMENT_ID  NUMBER(10, 0) NOT NULL,


    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_JOB_REF_JOBS FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID),
    CONSTRAINT FK_MANAGER_REF_MANAGERS FOREIGN KEY (MANAGER_ID)
        REFERENCES MANAGERS (MANAGER_ID),
    CONSTRAINT FK_DEPARTMENT_REF_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)

);

--

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 20, 30)
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 20, 30)
GROUP BY DEPARTMENT_ID
HAVING  AVG(SALARY) <= 5000;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 7500
ORDER BY DEPARTMENT_ID;

